name: Good Reads
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  bundleIdPrefix: com.jsryudev
targets:
  Good Reads:
    type: application
    platform: iOS
    deploymentTarget: 11.0
    sources: [Good Reads]
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxBlocking
      - carthage: SnapKit
      - carthage: Alamofire
      - carthage: Moya